apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml -o k8s/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: planspiegel-backend
  name: planspiegel-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: planspiegel-backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yaml -o k8s/
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: planspiegel-backend
    spec:
      imagePullSecrets:
        - name: gcr-secret
      containers:
        - env:
            - name: FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  key: FRONTEND_URL
                  name: env-docker
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: GOOGLE_CLIENT_ID
                  name: env-docker
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  key: GOOGLE_CLIENT_SECRET
                  name: env-docker
            - name: MINIO_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  key: MINIO_ACCESS_KEY
                  name: env-docker
            - name: MINIO_ENDPOINT_URL
              valueFrom:
                configMapKeyRef:
                  key: MINIO_ENDPOINT_URL
                  name: env-docker
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MINIO_ROOT_PASSWORD
                  name: env-docker
            - name: MINIO_ROOT_USER
              valueFrom:
                configMapKeyRef:
                  key: MINIO_ROOT_USER
                  name: env-docker
            - name: MINIO_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: MINIO_SECRET_KEY
                  name: env-docker
            - name: MXTOOLBOX_KEY
              valueFrom:
                configMapKeyRef:
                  key: MXTOOLBOX_KEY
                  name: env-docker
            - name: OPENAI_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: OPENAI_API_KEY
                  name: env-docker
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: env-docker
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: env-docker
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: env-docker
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PORT
                  name: env-docker
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: env-docker
            - name: REDIS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: REDIS_PASSWORD
                  name: env-docker
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  key: REDIS_URL
                  name: env-docker
            - name: SESSION_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: SESSION_SECRET_KEY
                  name: env-docker
          image: gcr.hrz.tu-chemnitz.de/planspiegel/planspiegel-app:latest
          livenessProbe:
            exec:
              command:
                - curl
                - -k
                - -f
                - https://localhost:8000/api/healthz
            failureThreshold: 5
            periodSeconds: 5
            timeoutSeconds: 5
          name: planspiegel-backend
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /backend
              name: planspiegel-backend-cm0
            - mountPath: /app/.env
              subPath: .env
              name: planspiegel-backend-cm1
            - mountPath: /app/.env.docker
              subPath: .env.docker
              name: planspiegel-backend-cm1
            - mountPath: /certs/cert.pem
              subPath: tls.crt
              name: planspiegel-backend-claim2
            - mountPath: /certs/key.pem
              subPath: tls.key
              name: planspiegel-backend-claim3
      restartPolicy: Always
      volumes:
        - configMap:
            name: planspiegel-backend-cm0
          name: planspiegel-backend-cm0
        - configMap:
            name: planspiegel-backend-cm1
          name: planspiegel-backend-cm1
        - name: planspiegel-backend-claim2
          secret:
            secretName: tls-secret
            items:
              - key: tls.crt
                path: tls.crt
        - name: planspiegel-backend-claim3
          secret:
            secretName: tls-secret
            items:
              - key: tls.key
                path: tls.key
