apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml -o k8s/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: planspiegel-backend
  name: planspiegel_backend
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: planspiegel-backend
