apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml -o k8s/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: planspiegel-postgres
  name: planspiegel_postgres
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: planspiegel-postgres
