services:
  planspiegel_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: planspiegel_backend
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    volumes:
      - .:/backend
      - .:/app
      - /etc/letsencrypt/live/planspiegel.com/fullchain.pem:/certs/cert.pem
      - /etc/letsencrypt/live/planspiegel.com/privkey.pem:/certs/key.pem
    networks:
      - backend_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "https://localhost:8000/api/healthz" ]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      - planspiegel_postgres
      - planspiegel_redis

  planspiegel_postgres:
    image: postgres:15
    container_name: planspiegel_postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    env_file:
      - .env.docker
    networks:
      - backend_network
    volumes:
      - planspiegel_postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 10s
      timeout: 5s
      retries: 5

  planspiegel_redis:
    image: redis:7
    container_name: planspiegel_redis
    ports:
      - "6379:6379"
    env_file:
      - .env.docker
    networks:
      - backend_network
    volumes:
      - planspiegel_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 2s
      retries: 5
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]

  #  planspiegel_minio:
  #    image: minio/minio
  #    networks:
  #      - backend_network
  #    ports:
  #      - "9000:9000"
  #      - "9001:9001"
  #    command: server /data --console-address ":9001"
  #    volumes:
  #      - minio_data:/data
  #    environment:
  #      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
  #      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
  #    healthcheck:
  #      test: [ "CMD", "mc", "ready", "local" ]
  #      interval: 5s
  #      timeout: 5s
  #      retries: 5

  planspiegel_migrations:
    build:
      context: .
      dockerfile: Dockerfile.migrations
    depends_on:
      - planspiegel_postgres
    env_file:
      - .env.docker
    networks:
      - backend_network
    volumes:
      - ./migrations:/app/migrations
    command: [ "alembic", "upgrade", "head" ]

networks:
  backend_network:
    driver: bridge

volumes:
  planspiegel_postgres_data:
  planspiegel_redis_data:
  minio_data:
